### PR TITLE
Juggernaut motions

### PR DESCRIPTION
**Pull request by FollowedFox**

### CODE REVIEW

**Comment by FollowedFox** [comment]
Please ignore the other two, Only dash attempt is the only one,
The dash actually does work, just set the 0f in the lerp statement to 30f, I felt like the static motion was too restricting,
- Remaining issue, air dashing

**Comment by FollowedFox** [comment]
Dashing locks motion to a certain motion, I feel like this can be a bit restricting, but I also feel like its more realistic

**Comment by FollowedFox** [comment]
Meant to also say SPACE is jump.

**Comment by FollowedFox** [comment]
image
Slight issue during the juggernaut falls from high places, legs want to say hello which causes isgrounded to think object in air, might cause some issues down the line with the dash script and potentially when we have damaged legs and we want to attempt a raiden

**Comment by Taliayaya** [comment]
Merged with #89

**Pull request closed without merging**
